name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
      target:
        description: 'Target to execute (leave empty for all)'
        required: false
        type: string

jobs:
  terraform:
    uses: egazzaneo/reusable-workflows/.github/workflows/terraform-pipeline.yml@main
    with:
      action: ${{ github.event.inputs.action || 'plan' }}
      target: ${{ github.event.inputs.target }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}